### ISSUE TITLE
build OCI image with `/app`

### ISSUE THREAD

**Issue by stb1337** [cap-js/incidents-app#56]
Hello colleagues,

i am able to run `incidents-app` locally and access the `/app` ui. 

When following https://cap.cloud.sap/docs/guides/deployment/to-kyma, I am able to build, push and deploy `incidents-app` on a BTP Kyma cluster but without the `/app` ui. 

How can I also include the `/app` into my build in order to have it available on my BTP Kyma cluster?

locally started `incidents-app`:
![image](https://github.com/cap-js/incidents-app/assets/5519671/a770418e-1d42-45a1-b5db-995c41272ec8)

deployed `incidents-app` on BTP Kyma:
![image](https://github.com/cap-js/incidents-app/assets/5519671/dc4409e1-1593-48a1-814f-7957d9b0f54d)

Cheers,
Steffen

**Comment by chgeo** [comment]
@cap-js/adapters @DanSchlachter  can you help here for the Kyma deployment?

@stb1337 please do not share SAP-internal site URLs here on github.com.  Either use external resources only, or use the SAP-internal channels like cap/issues for issues or SAP stack.

**Comment by navinkrishnan** [comment]
Hi @stb1337 ,
For running the application in BTP Kyma runtime, the recommendation is to push the UI (static content) to the HTML5 repository and use the Standalone or managed approuter to serve the content and consume the OData from srv.
Please follow the steps related to building UI deployer image.
https://developers.sap.com/tutorials/deploy-to-kyma.html#04fc0eb9-c42c-4145-ae54-e1e3c80b3fd8
